# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.define 'broker', primary: true do |broker|
    broker.vm.box = 'omu/debian-stable-server'

    broker.vm.network 'forwarded_port', guest: 2181, host: 2181, auto_correct: true
    broker.vm.network 'forwarded_port', guest: 9092, host: 9092, auto_correct: true
    broker.vm.network 'forwarded_port', guest: 9093, host: 9093, auto_correct: true

    broker.vm.provider :lxc do |lxc|
      lxc.customize 'cgroup.memory.limit_in_bytes', '2048M'
      lxc.customize 'net.0.ipv4.address', '10.0.3.15'
    end

    broker.vm.provision 'shell', path: 'install-kafka.sh'
  end

  config.vm.define 'client', primary: true do |client|
    client.vm.box = 'omu/debian-stable-server'

    client.vm.provider :lxc do |lxc|
      lxc.customize 'cgroup.memory.limit_in_bytes', '2048M'
      lxc.customize 'net.0.ipv4.address', '10.0.3.16'
    end

    client.vm.provision 'shell', path: 'install-client.sh'
  end
end
