# frozen_string_literal: true

Vagrant.configure('2') do |config|
  config.vm.box = 'omu/debian-stable-server'

  config.vm.network 'forwarded_port', guest: 2181, host: 2181, auto_correct: true # zookeeper
  config.vm.network 'forwarded_port', guest: 9092, host: 9092, auto_correct: true # plain
  config.vm.network 'forwarded_port', guest: 9093, host: 9093, auto_correct: true # ssl

  config.vm.provider :lxc do |lxc|
    lxc.customize 'cgroup.memory.limit_in_bytes', '2048M'
    lxc.customize 'net.0.ipv4.address', '10.0.3.15'
  end

  config.vm.provision 'shell', path: 'scripts/install-kafka.sh'
  config.vm.provision 'shell', path: 'scripts/install-client.sh'
  config.vm.provision 'shell', path: 'scripts/enable-ssl.sh'
end
